### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cs42** [upgradeya/redmine-contracts-with-time-tracking-plugin#1]
This looks really nice, but to be really useful for us we would need some additional features
- We need a way to _mark_ how many hours have been charged to the client already. Thus I have a quick overview, how much time has been done without an invoice yet.
- Make some things optional
  *\* purchase amount
  *\* start date, end date
- make the currency changeable

**Comment by partyp** [comment]
The currency request is a big one. We will be addressing that next. Closing this issue. Please see #53 #49  for currency discussions.
