### ISSUE TITLE
cannot add contract after install 1.2.0 in redmin 2.3.3 

### ISSUE THREAD

**Issue by jovett** [upgradeya/redmine-contracts-with-time-tracking-plugin#20]
the contacts tab shows and I added user as manager and nothing show up to allowing adding of contract 
![screen shot 2013-10-12 at 11 54 38 pm](https://f.cloud.github.com/assets/1069829/1321383/38405cd4-33bb-11e3-9afe-0d5f4fbbb18d.png)

**Comment by wesoccer2003** [comment]
Should work with the latest release. Let me know if you still have issues. Closing for now.
