### ISSUE TITLE
[Request] Put a preffix on table names

### ISSUE THREAD

**Issue by Oldzhay** [upgradeya/redmine-contracts-with-time-tracking-plugin#23]
Hello there,
I've been using Redmine contracts plugins for a while (ver 1.0.0), but now, upgrading to 1.2.0 it gave me an error, while trying to create expenses table, because it already exists (in another plugin).

So I would like to ask to change the table name adding a prefix (something like contracts_expenses, contracts_... and so on

Regards

**Comment by wesoccer2003** [comment]
The expenses table is now renamed to contracts_expenses in the v2.1.0
