### ISSUE TITLE
issues with creating expenses

### ISSUE THREAD

**Issue by dmp1ce** [upgradeya/redmine-contracts-with-time-tracking-plugin#28]
"i attached the new file and the errorlog.
Basicly I edited 4 lines of code a little bit."

expenses_controller.rb - https://drive.google.com/file/d/0B81pCkZYSnYEdWlnT1FibTBxRldlQnh4WXU1dlVvc3JIOUxV/edit?usp=sharing
errorlog - https://drive.google.com/file/d/0B81pCkZYSnYEWjNfczNhalY3VnJaUTB3M1o5TUFfVldqTnlB/edit?usp=sharing

**Comment by wesoccer2003** [comment]
Fixed, committed, and pushed. Thanks Dave!
