### ISSUE TITLE
Problem at install with reminecrm invoices

### ISSUE THREAD

**Issue by jorge2esteban** [upgradeya/redmine-contracts-with-time-tracking-plugin#31]
When installa a plugin

the rake abort becuase the table expenses exist ???

is possible modify the name of tables por example contracts_....

**Comment by wesoccer2003** [comment]
I'm not sure what is in your expenses table, but if you can delete it, then it should allow you to install after its gone.

**Comment by wesoccer2003** [comment]
The expenses table is now renamed to contracts_expenses in the v2.1.0
