### ISSUE TITLE
Redmine 3.2.0

### ISSUE THREAD

**Issue by Pi3R1k** [upgradeya/redmine-contracts-with-time-tracking-plugin#33]
contract plugin work well with redmine 2.6.9 but whith redmine 3.2.0, i have these error : 
```
Started GET "/projects/projet/contracts" for 88.175.116.19 at 2015-12-17 18:02:11 +0100
Processing by ContractsController#index as HTML
  Parameters: {"project_id"=>"projet"}
  Current user: pierrick (id=128)
Completed 500 Internal Server Error in 30ms (ActiveRecord: 17.9ms)

ArgumentError (wrong number of arguments (1 for 2..3)):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

sudo_mode seems to be a new feature of readmine 3.1 and more

**Comment by wesoccer2003** [comment]
The plugin is currently not supported for Redmine version 3, but we are working on that. Hopefully it will be completed within the next month.

-Wesley Jones
 

    On Thursday, December 17, 2015 12:11 PM, Pi3R1k <notifications@github.com> wrote:
 

 contract plugin work well with redmine 269 but whith redmine 320, i have these error : Started GET "/projects/projet/contracts" for 8817511619 at 2015-12-17 18:02:11 +0100
Processing by ContractsController#index as HTML
  Parameters: {"project_id"=>"projet"}
  Current user: pierrick (id=128)
Completed 500 Internal Server Error in 30ms (ActiveRecord: 179ms)

ArgumentError (wrong number of arguments (1 for 23)):
  lib/redmine/sudo_moderb:63:in `sudo_mode'
sudo_mode seems to be a new feature of readmine 31 and more—

**Comment by wesoccer2003** [comment]
Redmine 3 compatible now.
