### ISSUE TITLE
Installation Fails with Redmine 3.2.0-1

### ISSUE THREAD

**Issue by bjoernhoeper** [upgradeya/redmine-contracts-with-time-tracking-plugin#35]
When using the Bitnami Redmine Stack under Ubuntu Server 14.04LTS the installation of the plugin fails with the message:

`LoadError: No such file to load -- contract_category`

Used files from the zip archive under: 
https://github.com/upgradeya/redmine-contracts-with-time-tracking-plugin/archive/master.zip 
which have been extracted to the plugins folder of the Redmine installation directory (for Bitnami stack {install dir}/apps/redmine/htdocs/plugins). Plugin version is 2.0.1.

**Comment by hvstudio** [comment]
Confirmed.

**Solution:**
Rename directory to "contracts" only and before runing rake check existence of database table "expenses" it need to be deleted,than run rake and restart apache2

**Comment by bjoernhoeper** [comment]
Worked like a charm this way.

Maybe it should be mentioned in the Readme.md?

**Comment by wesoccer2003** [comment]
The expenses table is now renamed to contracts_expenses in v2.1.0 so it shouldn't happen anymore.
