### ISSUE TITLE
Change contract name

### ISSUE THREAD

**Issue by hisie** [upgradeya/redmine-contracts-with-time-tracking-plugin#36]
This project is fantastic, i have just started to work with it and i like i a lot.

I think i would better if, when creating the contract, you can manually give a name to the contract in a property way like "Server maintenance" instead of "name-of-project_Maint#001".

Thank you.

**Comment by wesoccer2003** [comment]
Agreed. I will try and make this change soon.

**Comment by thomashempel** [comment]
We need this!

**Comment by jthebert** [comment]
+1

**Comment by barglm** [comment]
+1

**Comment by partyp** [comment]
Awesome guys, we will get @wesoccer2003 on this! Thanks for the feedback.

**Comment by partyp** [comment]
Hello everyone! 

We were going to add a "contract name" field which will override the current display completely as @hisie has described. 

I was curious - Do any of you want the contract number appended to the end of the "contract name" field?

**Comment by wesoccer2003** [comment]
The title field is back. All previous titles stored in the database should be visible, plus all new contracts can have their own custom name. The change is made in the plugin's version 2.3.
