### ISSUE TITLE
Czech Translation + Missing string

### ISSUE THREAD

**Issue by barglm** [upgradeya/redmine-contracts-with-time-tracking-plugin#39]
Hi,
I am attaching Czech translation +, there's one missing translation in 
/contracts/app/views/contracts/_form.html.erb:24

In translation, I used "label_contractors_rates" 

[cs.zip](https://github.com/upgradeya/redmine-contracts-with-time-tracking-plugin/files/243671/cs.zip)

**Comment by wesoccer2003** [comment]
Thanks barglm! Translation has been added and the missing string.
