### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by Hesiode** [upgradeya/redmine-contracts-with-time-tracking-plugin#41]
Hi, i have download zip, copy and rename in contracts in plugins redmine directory.
And do : rake redmine:plugins:migrate RAILS_ENV=production
I think all is ok :
[`Migrating contracts (Redmine Contracts With Time Tracking)...
== 1 CreateContracts: migrating ===============================================
-- create_table(:contracts)
   -> 0.0233s
== 1 CreateContracts: migrated (0.0234s) ======================================

== 2 AddContractIdToTimeEntries: migrating ====================================
-- add_column(:time_entries, :contract_id, :integer)
   -> 0.0208s
== 2 AddContractIdToTimeEntries: migrated (0.0209s) ===========================

== 3 AddPrecisionToHourlyRate: migrating ======================================
-- change_column(:contracts, :hourly_rate, :decimal, {:precision=>16, :scale=>2})
   -> 0.0053s
== 3 AddPrecisionToHourlyRate: migrated (0.0054s) =============================

== 4 CreateUserProjectRates: migrating ========================================
-- create_table(:user_project_rates)
   -> 0.0022s
== 4 CreateUserProjectRates: migrated (0.0023s) ===============================

== 5 CreateUserContractRates: migrating =======================================
-- create_table(:user_contract_rates)
   -> 0.0020s
== 5 CreateUserContractRates: migrated (0.0021s) ==============================

== 6 CreateExpenses: migrating ================================================
-- create_table(:expenses)
   -> 0.0023s
== 6 CreateExpenses: migrated (0.0024s) =======================================

== 7 Lock: migrating ==========================================================
-- add_column(:contracts, :is_locked, :boolean, {:default=>false})
   -> 0.0040s
-- add_column(:contracts, :hours_worked, :float, {:length=>8, :decimals=>2})
   -> 0.0040s
-- add_column(:contracts, :billable_amount_total, :float, {:length=>8, :decimals=>2})
   -> 0.0036s
== 7 Lock: migrated (0.0248s) =================================================

== 8 ProjectContractId: migrating =============================================
-- add_column(:contracts, :project_contract_id, :integer, {:default=>1})
   -> 0.0038s
== 8 ProjectContractId: migrated (0.0379s) ====================================

== 9 ContractCategoryEnumeration: migrating ===================================
-- add_column(:contracts, :category_id, :integer)
   -> 0.0040s
== 9 ContractCategoryEnumeration: migrated (0.0583s) ==========================

== 10 RenameExpenses: migrating ===============================================
-- rename_table(:expenses, :contracts_expenses)
   -> 0.0013s
== 10 RenameExpenses: migrated (0.0014s) ======================================](url)
`

But i have nothing in redmine, plugins part (see screenshot)
![selection_029](https://cloud.githubusercontent.com/assets/5263119/15893516/7b31fd10-2d80-11e6-8c82-c54c4e6e6520.png)

Thank you for your help
Redmine 3.1.2

**Comment by Hesiode** [comment]
Ok, just restart apache and its ok

**Comment by wesoccer2003** [comment]
Ok great! Glad it works.
