### ISSUE TITLE
  require_dependency 'contract_category' 45	

### ISSUE THREAD

**Issue by bluenevus** [upgradeya/redmine-contracts-with-time-tracking-plugin#46]
I get an error that it   require_dependency 'contract_category' 45

it won't install because this dependency can't be found

redmine 3.2 redmine 3.3

**Comment by wesoccer2003** [comment]
Hey bluenevus, can you check if that dependency exists? It is referencing a file within the plugin. Check your plugins folder for `contracts/app/models/contract_category.rb`.

**Comment by bluenevus** [comment]
rake aborted!
LoadError: No such file to load -- contract_category
/var/lib/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'

**Comment by bluenevus** [comment]
the file is there though

**Comment by bluenevus** [comment]
got it.  folder needs to be renamed to contracts.  next I had redminecrm plugin invoices installed.  didn't work because of a conflict in the table expenses it creates with the expense table this plugin creates.  got it working

**Comment by wesoccer2003** [comment]
Ok cool. Yea, sorry about that. I just made a change to resolve that conflict with that table names, so feel free to grab the latest code if you have issues with the expenses table.
