### ISSUE TITLE
Add Dutch translation (nl.yml supplied)

### ISSUE THREAD

**Issue by martijnv** [upgradeya/redmine-contracts-with-time-tracking-plugin#50]
I've created a nl.yml with Dutch translations for the contracts plugin. See the attached nl.txt (rename to .yml off course).
[nl.txt](https://github.com/upgradeya/redmine-contracts-with-time-tracking-plugin/files/681946/nl.txt)

**Comment by martijnv** [comment]
Here is a new version of the nl.yml (rename to .yml again of course) based on a checkout of the latest HEAD
[nl.txt](https://github.com/upgradeya/redmine-contracts-with-time-tracking-plugin/files/763489/nl.txt)

**Comment by martijnv** [comment]
I corrected a typo and saved the fil in UTF-8 encoding, otherwise Redmine would crash when importing the translations.
[nl.txt](https://github.com/upgradeya/redmine-contracts-with-time-tracking-plugin/files/763546/nl.txt)

**Comment by wesoccer2003** [comment]
Thanks Martijn! I have added it to the project.
